### ISSUE TITLE
打包时报错：[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by Eastboat** [vuepress-reco/vuepress-theme-reco-1.x#416]
- [ ] I confirm that this is an issue rather than a question.

## Bug report

npm run  build时报一个路由错误，之前使用1.x版本挺好的， 最近突然就这样.....

> npm run build Times a routing error, before using 1.x version is fine, recently suddenly like this.....

#### What is actually happening?
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Anonymous>
               <GlobalLayout>
                 <Root>
// ......
// ......
error Error rendering /docs/theme-reco/api.html: false
undefined
error Error rendering /docs/theme-reco/axios.html: false
undefined
error Error rendering /docs/theme-reco/theme.html: false
undefined
error Error rendering /docs/theme-reco/plugin.html: false
undefined
error Error rendering /docs/theme-reco/: false
undefined
TypeError: Cannot read property 'match' of undefined
    at ensureExt (node_modules/_vuepress-theme-reco@1.6.16@vuepress-theme-reco/helpers/utils.js:35:25)
    at 0.server-bundle.js:1683:92
```

![WX20221209-160826@2x](https://user-images.githubusercontent.com/38577428/206658686-6b3ae7d8-873c-4b5b-ae1a-6bbb176d6314.png)

#### Other relevant information

- Your OS: MacOS Big Sur
- Node.js version: 15.14.0
- VuePress version: 1.8.2
- VuePress-theme-reco version: 1.6.10
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? npm & cnpm

**Comment by H-TWINKLE** [comment]
同样遇到问题

**Comment by recoluan** [comment]
建议升级2.0吧，1.0不维护了
